### ISSUE TITLE
Toast scaling issue

### ISSUE THREAD

**Issue by Merathilis** [ls-/ls_Toasts#25]
Hello Senior,

first of all, thank you for the new skinning function for ls_Toast. But i have an issue if you set the scale to 0.9, then the right border seems to be cut off. With the default skin it looks fine, but even with the implement ElvUI skin, it get cut off:

See Screenshots
Scale 1.0 (fine)
![1 0](https://user-images.githubusercontent.com/272403/36198291-75bc71b8-1176-11e8-9278-addac96869b3.png)

Scale 0.9 (cut off)
![0 9](https://user-images.githubusercontent.com/272403/36198315-83a23498-1176-11e8-97a3-d17393e4c971.png)

btw. here is the code to my skin: https://git.tukui.org/Merathilis/ElvUI_MerathilisUI/blob/development/ElvUI_MerathilisUI/modules/skins/addons/ls_Toasts.lua

**Comment by ls-** [comment]
First of all, new skin engine isn't live yet, so don't release the skin! :D 

It happens because of scaling, I use `toast:SetScale(scale)` w/o any smart maths, so it's not exactly cut off, it just happens to be on a half-pixel, and given that the texture is only 1px wide it "disappears". 

If you move toasts around the screen, you'll notice that other edges will get "cut off" as well. So for perfect-pixel UIs and skins I recommend to set scale to 1.

Also, regarding `texture = "Interface\\AddOns\\ElvUI_MerathilisUI\\media\\textures\\toast-border",` new borders use the same type of texture as [backdrop's edgeFile](https://wow.gamepedia.com/EdgeFiles). The addon creates [custom backdrop-like borders](https://github.com/ls-/ls_Toasts/blob/master/core/toast.lua#L30-L141).

In your case, if you want black borders you may want to do either of these:
- Disable border colouring in options and define border as:
```Lua
border = {
	color = {1, 1, 1},
	offset = 0,
	size = 1,
	texture = {1, 1, 1, 0.75},
},
```
This will create a white border semi-transparent border that's coloured black by default, but can be coloured via `:SetVertexColor` later.
- Define border as:
```Lua
border = {
	offset = 0,
	size = 1,
	texture = {0, 0, 0, 0.75},
},
```
This will create a permanently black semi-transparent border, RIP `:SetVertexColor`:grin::gun:

**Comment by ls-** [comment]
What does [this bit](https://git.tukui.org/Merathilis/ElvUI_MerathilisUI/blob/development/ElvUI_MerathilisUI/modules/skins/addons/ls_Toasts.lua#L100-105) do? O_o

And another queston, is this `0.15, 0.15, 0.15, .75` the colour you use in elvUI for backgrounds? My tests showed me `0.06, 0.06, 0.06, 0.8` >_>

**Comment by Merathilis** [comment]
Thx for the quick respond and for your clarification. I will use the black semi-transparent border :P

Another question, when can we expect the release? And no, the color you use should be fine. I use this in my plugin. ;)

**Comment by Merathilis** [comment]
Oh, and here is my styling function you asked: https://git.tukui.org/Merathilis/ElvUI_MerathilisUI/blob/development/ElvUI_MerathilisUI/core/functions.lua#L192

**Comment by Merathilis** [comment]
Oh, and i will close this issue as it is then not an issue at all :D

**Comment by ls-** [comment]
Prob this weekend. I want to move many methods from `E` to `P` table because there's no need for them to be public. 

BTW, here's a cleaned-up version of your skin table w/ colourable borders :D 

```Lua
LST:RegisterSkin("MerathilisUI", {
	name = "|cffff7d0aMerathilisUI|r",
	template = "elv-no-art",
	border = {
		texture = {1, 1, 1, 0.75},
	},
	icon = {
		tex_coords = {.08, .92, .08, .92},
	},
	icon_border = {
		offset = 1,
		texture = {1, 1, 1, 0.75},
	},
	icon_highlight = {
		hidden = true,
	},
	icon_text_1 = {
		flags = "OUTLINE",
	},
	icon_text_2 = {
		flags = "OUTLINE",
	},
	dragon = {
		hidden = true,
	},
	slot = {
		tex_coords = {.08, .92, .08, .92},
		texture = "Interface\\AddOns\\ElvUI_MerathilisUI\\media\\textures\\icon-border",
	},
	bg = {
		alliance = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		archaeology = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		collection = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		default = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		dungeon = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		horde = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		legendary = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		legion = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		recipe = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		store = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		transmog = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		upgrade = {
			texture = {0.15, 0.15, 0.15, .75},
		},
		worldquest = {
			texture = {0.15, 0.15, 0.15, .75},
		},
	},
})
```

**Comment by Merathilis** [comment]
cool, thx ;)

**Comment by ls-** [comment]
@Merathilis didn't notice that you wanted perma-black borders before doing the cleanup 😁:gun:

```Lua
border = {
	texture = {0, 0, 0, 0.75},
},
icon_border = {
	offset = 1,
	texture = {0, 0, 0, 0.75},
},
```
