### ISSUE TITLE
Toasts for Experience and Reputation Gains

### ISSUE THREAD

**Issue by Industrial** [ls-/ls_Toasts#36]
Hi!

I'd love to get a toast for Experience Gains and Reputation Gains.

I have them in chat now but I would like a toast instead :-)

Edit: You could do fancy stuff like "repetitions to level" and "repetitions to new Reputation level (revered, exalted, etc)".

gr,

Tom

**Comment by ls-** [comment]
Hi! Aaaand sorry for the VERY late reply, I haven't been playing WoW for quite some time T_T 8.2 hit me hard >_>

I think this issue/request was brought up some time ago somewhere, prob in comments on WoWI/Curse, I don't really want this kind of feature in this addon because these types of gains are really spammy, for instance, xp gains happen all the time, the same goes for rep gains, and they aren't important/significant enough. 

That's also the reason why I didn't include toasts for honour or azerite/artefact power gains.
