### ISSUE TITLE
achievement Blizzard default toasts don't show up [WotLK]

### ISSUE THREAD

**Issue by vyrnius** [ls-/ls_Toasts#47]
Hej!

I really enjoy your addon... it's great and already recommend it to some guild mates! 
But I still like the blizzard default toasts for achievements (are they called toasts?) and I would like to keep them together with the other toasts from your addon... is this possible?
If I deactivate achievement toasts from your addon I don't get (achievement) toasts at all :-/

thank you very much!

**Comment by ls-** [comment]
Hi!

Unfortunately it's impossible to mix them, it's even mentioned in the [FAQ](https://github.com/ls-/ls_Toasts#faq).

However, I'm planning to add a unique overlay to achievement toasts that resembles what Blizz toasts have.

![](https://user-images.githubusercontent.com/2725970/197732880-7300590a-e537-49b0-8773-da21e0660ba4.PNG)

After it's done you can just show achievements in a different anchor or something so that they stand out more.

**Comment by ls-** [comment]
Old:
![image](https://user-images.githubusercontent.com/2725970/199520909-d9707bcd-7898-44db-8b4a-0f08a939f4dc.png)
![image](https://user-images.githubusercontent.com/2725970/199521915-897f63bc-2d22-4339-a575-287e6c29f343.png)

New:
![image](https://user-images.githubusercontent.com/2725970/199521753-64207832-8bbd-432b-abda-af82252fe87b.png)
![image](https://user-images.githubusercontent.com/2725970/199521779-3e3d056f-9d0b-4ad7-a49d-8df17959daa3.png)

This is my attempt to make my achievement toasts a bit fancier. A compromise of sorts because I'm def not reenabling Blizz achievement toasts.
