### ISSUE TITLE
Change font size depending on frame

### ISSUE THREAD

**Issue by mapleleaf202324** [ls-/ls_Toasts#58]
Hello, I have a question or request.

I had seen that my friend always uses 2 or even 3 frames. One for just loot, another for just gold, etc. He travels a lot in the AH.

I have set it up that way and have 2 frames. One that shows the "general loot" and is scaled slightly smaller. And a frame for everything else that is scaled larger.

Now my question/request: Could you add the option that you could adjust the font size depending on the frame? Since I have scaled both frames differently and you only adjust the font size for all frames with "general", the font size is then too big in the small frame or too small in the large frame.

I hope you understand what I mean. Or did I miss the option?

PS: Thanks for the great work.

**Comment by ls-** [comment]
Hi!

I'm not exactly sure what you mean... I do use standard scaling, so the fonts should scale accordingly:

![image](https://github.com/ls-/ls_Toasts/assets/2725970/de75b05f-174a-4a56-8669-286acb58383d)

The left column uses 0.8 scale and the right one uses 1.2.

Settings like that sizing and whatnot for each individual toast type are definitely not happening, I originally developed this addon exactly because I didn't like how all over the place Blizz toasts were 😅 That's why scaling in particular is set at the anchor this way people can have a high priority larget toasts elsewhere on the screen separately from the other toasts.

**Comment by ls-** [comment]
Btw, while taking screenshots for my reply I found a bug in my anchor system, and so while it's unrelated to your question, thanks anyway 😅

**Comment by mapleleaf202324** [comment]
First of all thanks for the reply.

Yes, the font scales, but I find the font in the frame on the right to be a bit large and would like the font for the large scaled frames to be smaller.
But if I change the font in the large frame, the font in the small frame becomes even smaller and unfortunately you can hardly read it anymore. Here's a picture:

![image](https://github.com/ls-/ls_Toasts/assets/155015889/577c4ebb-5669-432a-afff-15ec9c73e18d)

Therefore my question is whether you can add an option to adjust the font size for each frame.
But if that's not possible, I'll get used to it somehow. :)

And about the error: You're welcome. :D lol

**Comment by ls-** [comment]
Oh, oki, then I understood you correctly. This definitely isn't happening, all toasts regardless of their type or anchor they're attached to are pulled from one common pool, then they're returned to said pool after they disappear to be reused again and again.

The only things that actually change on the fly are the colours and visibility of some toast elements, everything else is set when the toast is first created, and it stays that way until you start swapping skins because it's a somewhat extensive and thus laggy process. That's why you sometimes get fps drops/hiccups when A LOT of toasts appear at once, it happens because many toasts are created at once, but aside from the initial hiccup on their creation, reusing toasts is pretty cheap because at that point all I need to do is to reset the colours which is literally whatever.

I designed it this way on purpose, and I have no plans to change it, as I said, a greater visual consistency is the reason this addon exists in the first place.
