### ISSUE TITLE
release 100207.01 has asset with broken paths

### ISSUE THREAD

**Issue by torkus** [ls-/ls_Toasts#60]
The asset for release [100207.01](https://github.com/ls-/ls_Toasts/releases/tag/102007.01) appears to have it's file paths broken.

**Comment by tflo** [comment]
Can confirm. 

Downloading and expanding the zip manually creates the correct structure.

**Comment by ls-** [comment]
This is really weird. Are you two on mac by any chance?

**Comment by ls-** [comment]
Oki, got it. I'll switch back to 7z for creating archives, I recently switched to built-in tool that's used by powershell to keep things more self-contained, and this issue seems to be the result of that...

Also, @tflo I don't use any automation for addon publishing because I simply can't be trusted around the automation that goes beyond my local machine. I literally have to ask people in oUF team to tag releases for me because I managed to mess even that up a few years ago, so I just stay away from it 😅 That said I automate most things that happen locally...

**Comment by tflo** [comment]
> I managed to mess even that up a few years ago, so I just stay away from it

OK :) In case you change your mind, it's a really easy setup. On your CF Project page, just select the appropriate packaging rule:

<details>
<summary>Setup screenshot</summary>
<img width="749" alt="image" src="https://github.com/ls-/ls_Toasts/assets/1410282/208a431f-7c01-4071-8be5-9e345c6a3405">

</details>

**Comment by ls-** [comment]
Oh, no, don't get me wrong, ik how it works, I can set it up, etc... That's not the problem 🤣 The problem happens afterwards...

oUF is a UF framework that's used by many addons to simplify the unit frame creation process, like, even ElvUI uses it. And on our team there's a guy who's basically an automation guru, this kind of stuff is also a part of his actual job, but even someone like him couldn't stop my sorry ass from messing up something as simple as tagging on master 🤣

So yeah, there's some some thing I just shouldn't touch 🤭

**Comment by tflo** [comment]
OK.

To keep automation completely locally, you could also give the [BigWigs packager](https://github.com/BigWigsMods/packager) a try. I use this for GH releases / Wago uploads and it creates correct zips (on a Mac at least ;)

**Comment by ls-** [comment]
Trust me, I'm aware of that one. It's not that I don't want to automate things, I do, and I do that locally, I just don't want to automate the publishing process because I'll 1000% fuck it up, it's not if, it's not when, I just will 😱

And I don't create my archives manually either, [I have a script that handles this stuff for me](https://github.com/ls-/ls_Toasts/blob/master/.compressor.ps1), like, it takes what it needs, removes all the unnecessary stuff, and then creates an archive. I often use it to quickly zip things to send it to someone for testing when I'm dealing with a bug I can't repro, so it's not just for publishing.

However, I recently switched to powershell's built-in tools instead of using 7zip for the archive creation step because I just wanted things to be more self-contained, like, what if reinstalled windows and didn't install 7zip or something? I write my scrips in powershell/posh, `Compress-Archive` is the command, however, whatever it uses under the hood to create zips creates zips that seemingly don't work properly on macs. And that's the cause of the issue we're dealing with here. So the next step is to switch back to 7zip for that step in my script.

I'll do it tomorrow, there's some other bug reports I have to deal with first as well 😭

**Comment by tflo** [comment]
> Trust me, I'm aware of that one.

No worries, I'll stop with my recommendations right now 🤐🙄

Oh, and thanks for the nice addon, which I'm using for years!

**Comment by ls-** [comment]
> No worries, I'll stop with my recommendations right now 🤐🙄

I mean, I've been writing addons for a scary amount of time >_> I'm aware of all the ways you can automate the addon update publishing process for gh/curse/wago/etc. But I'm not using them not because I don't like them or I don't know how to use them, I'm not using them because my sorry ass will 1000% fatfinger something, and it'll happen sooner rather than later 🤣 So I'm not being dismissive, I actually appreciate that you took your time to recommend things, but I'm just a mess like that, so it's safer not to use them.

And the issue at hand is honestly bizarre. Like, you'd expect a multi-trillion dollar company to have a reliable utility to create zip archives that work across multiple OSes as expected, it's not like zips are something new or exclusive to just one OS. And yet here we are, smdh 😒

> Oh, and thanks for the nice addon, which I'm using for years!

Hehe, thanks!

Btw, could you test [this archive](https://github.com/user-attachments/files/15522883/ls_Toasts-100207.01.zip) for me? Just want to be sure...

**Comment by tflo** [comment]
Your linked archive expands apparently correctly to this tree:

<img width="201" alt="image" src="https://github.com/ls-/ls_Toasts/assets/1410282/97fc12a3-6a6e-4969-aba4-9f3dfbff411a">

But note that also with your problematic release, manually expanding the zip (from CF) on my Mac (via the OS's Archive Utility.app) worked fine, it was just the installation via the CF app that expanded all files flat into the AddOn directory.

> And the issue at hand is honestly bizarre.

Well, I'm using Macs since around 1994, and I remember that there have been always the more or less occasional glitches with ZIP archives from Win boxes, especially, but not only, in the times before macOS switched to zip as standard archive format. Namely a Win app "WinZip" was notorious for creating archives that caused issues for the Mac expanders (well, at least some decades ago…). But yeah, a bit surprising to see those issues again…

**Comment by ls-** [comment]
But does it extract properly? 🙏🏼

**Comment by tflo** [comment]
The file tree seems OK and the files have Lua content, so I would say yes :)

I can also check if the addon is working, give me a sec…

**Comment by tflo** [comment]
Yeah, the addon loads fine…

<img width="242" alt="image" src="https://github.com/ls-/ls_Toasts/assets/1410282/09a7aa0b-62f6-4c7b-8bc9-bd76c9b0bbdf">

… without errors and I can open the config without issues.

**Comment by ls-** [comment]
Who would win? A multi-trillion dollar company or a single Russian freelance programmer (7zip creator)? 🤣 Now we know the answer.

Fucking hell, bruv, I switched to powershell built-in tools because I actually expected that shit to work in 2024, and yet here we are...

**Comment by tflo** [comment]
Yes, this is true, the 7z app always created "good" archives. I remember that I used to recommend it to Win people who had sent me incompatible zips.

I just tried your problematic release again, installing via the CF app, to see if it was maybe a temporary CF glitch, but no.

**Comment by ls-** [comment]
K, pushed an update for my script, now I'll need to update it elsewhere, smdh...

Thanks for your time, and good night, it's already 2am here 😴

**Comment by tflo** [comment]
It seems this describes your Compress-Archive issue:

https://superuser.com/questions/1382839/zip-files-expand-with-backslashes-on-linux-no-subdirectories

Just weird that I can manually expand your zip from CF correctly (eg. with Archive Utility, and also with the `unzip` BSD command line tool), but the CF installer app cannot handle it.

**Comment by torkus** [comment]
The [linked archive](https://github.com/ls-/ls_Toasts/issues/60#issuecomment-2143537868-permalink) also looks correct to me.

> This is really weird. Are you two on mac by any chance?

Linux, however the archive appeared to extract correctly. It was Go code that was having problems finding a subdirectory within that release.

Good to hear a solution was found, thanks guys.

**Comment by ls-** [comment]
Released 100207.02 that's packed by 7zip, so it should be fine now.

**Comment by tflo** [comment]
Confirmed, everything back to normal 😄, 100207.02 correctly expanded by the CF app:

<img width="393" alt="image" src="https://github.com/ls-/ls_Toasts/assets/1410282/8a345e01-5590-4f7c-958d-e2557274be9d">
