### ISSUE TITLE
Sound from filtered achievements still plays

### ISSUE THREAD

**Issue by Taizunz** [ls-/ls_Toasts#70]
I've noticed that the sound for filtered guild achievements still plays. Is this something you're able to block out with an update as well?

**Comment by ls-** [comment]
The sound is on the character, it's not a part of the UI, so I chose not to mess with it since it's beyond the scope of the addon. That's also why there's no sound toggle for achievements in general. It's possible to mute the sound globally via `MuteSoundFile(569143)`, but it'll affect ALL achievements.

There's a bunch of addons that do the filtering for the default UI, like, they suppress default toasts and chat messages, and some of them also mute the sound with a timer so it doesn't affect other achievements as much. [Guild Achievements Fix](https://www.curseforge.com/wow/addons/guild-achievements-fix) is pretty good in terms of code. It's simple and it does what it sets out to do, no extra bells and whistles.

**Comment by ls-** [comment]
And ib4 "why don't you add the global mute to the addon?". I considered it in the past, but it's not worth it. I have 0 control over it, even if I add it, it's a very common feature in other addons from leatrix to specialised addons like above, so they'll be enabling/disabling the sound regardless of what it's set to in my config, and I'll be getting the reports saying that the "Sound Effects" toggle doesn't work.

**Comment by ls-** [comment]
Well, looks like Blizz themselves decided to finally fix it :D

https://worldofwarcraft.blizzard.com/en-us/news/24134803/hotfixes-september-27-2024

**Comment by Taizunz** [comment]
Oh wow. It only took how many years? :D

**Comment by ls-** [comment]
They fixed it because it caused multiple wipes during this RWF 😅 Under certain circumstances it could cause a rather nasty freeze for a sec or two, and this resulted in multiple wipes live on stream on the official WoW channel which, needless to say, is no bueno 🤣
