### ISSUE TITLE
Any plans for new skins?

### ISSUE THREAD

**Issue by ZaViper** [ls-/ls_Toasts#72]
I was wondering if there is any plans to add new skins in the future. If possible it would be amazing if there was a skin that can match AzeriteUI's style. (https://www.curseforge.com/wow/addons/azeriteui)

**Comment by ls-** [comment]
I'll look into it, but no promises.

**Comment by ls-** [comment]
I talked to goldpaw about it because I needed to adjust his textures to make them work in my addon, and he gave me the permission to do that.

I tweaked his tooltip and aura border textures
![image](https://github.com/user-attachments/assets/80b99ece-d7e8-4089-b175-cac2534860b8)

and that's what I have now
![image](https://github.com/user-attachments/assets/ab0c13d5-bea4-429e-a6e7-176e9cfb41c2) 
![image](https://github.com/user-attachments/assets/cc4c8998-bdde-4ac5-86d0-cf9cf99c5a58)

**Comment by ZaViper** [comment]
Oh wow! This is amazing thank you! I honesty wasn't expecting it to happen because I know it's possibly a huge task. I really appreciate it!

**Comment by ls-** [comment]
Yeah, there's a few issues, but it's not that big of a deal overall.

**Comment by ls-** [comment]
Released 110005.01 which includes the new skins. Just saying.

**Comment by ZaViper** [comment]
Thank you so much, I quickly updated it and now enjoying the new look!
